### ISSUE TITLE
Uptrernds_monitor_web mode only accepts "Production"

### ISSUE THREAD

**Issue by GeorgeGlarakis** [wasfree/terraform-provider-uptrends#12]
### Terraform Version
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/wasfree/uptrends v0.1.1

### Affected Resource(s)
- uptrends_monitor_web

I haven't tried with a different resource.

### Terraform Configuration Files
```hcl
resource "uptrends_monitor_web" "testing-api" {
  name                     = "api"
  check_interval           = 2
  notes                    = "Managed by Terraform"
  primary_checkpoints_only = true
  type                     = "Https"
  mode                     = "Development"

  url                       = "https://www.google.com/"
  expected_http_status_code = 200
}
```

### Debug Output
https://gist.github.com/GeorgeGlarakis/48872a89c7e0f49e3e42db6aa4e1ee57

### Terminal Output
https://gist.github.com/GeorgeGlarakis/6023335c4c4fb09aa140093ca19149bf

### Expected Behavior
What should have happened?

It should have been accepted the mode "Development".

### Actual Behavior
What actually happened?

Throws an error without any specific explanation and turns out that it does not accept other modes than "Production".

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by wasfree** [comment]
Hi @GeorgeGlarakis,

Thanks for bringing this up.

Monitors in development mode are always inactive. You can’t schedule monitor in development mode for execution, so the monitor won’t generate any results in the monitor log. Unfortunately this Message":`"Invalid combination of settings: development or staging mode and generating alerts."` is supressed if not running in debug mode.

It should work if you set `is_active = false` when mode is Development:
```
resource "uptrends_monitor_web" "testing-api" {
  name                     = "api"
  check_interval           = 2
  notes                    = "Managed by Terraform"
  primary_checkpoints_only = true
  type                     = "Https"
  mode                     = "Development"
  is_active                = false

  url                       = "https://www.google.com/"
  expected_http_status_code = 200
}
```

In paralell the error message output has to be improved.  Please let me know if you have any further questions.

**Comment by GeorgeGlarakis** [comment]
### Reply
Unfortunately , it still doesn't work by adding the `is_active` flag.

You can find below the debug output from `terraform apply`.

### Terraform Configuration Files
```hcl
resource "uptrends_monitor_web" "testing-api" {
  name                     = "api"
  check_interval           = 2
  notes                    = "Managed by Terraform"
  primary_checkpoints_only = true
  type                     = "Https"
  mode                     = "Development"
  is_active                = false

  url                       = "https://www.google.com/"
  expected_http_status_code = 200

}
```

### Debug Output
https://gist.github.com/GeorgeGlarakis/0e0543db5902279e2b45621326e7edce

**Comment by wasfree** [comment]
Hi @GeorgeGlarakis,

sorry, you also need to set `generate_alert=false` when `mode="Development"`. This error message: {"Messages":[{"Message":"Invalid combination of settings: development or staging mode and generating alerts."}] is not directly visible. The error messages will be improved soon, until then you can run `TF_LOG=DEBUG terraform apply`.

```
resource "uptrends_monitor_web" "testing-api" {
  name                     = "api"
  check_interval           = 2
  notes                    = "Managed by Terraform"
  primary_checkpoints_only = true
  type                     = "Https"
  mode                     = "Development"
  is_active                = false
  generate_alert           = false

  url                       = "https://www.google.com/"
  expected_http_status_code = 200
}
```

**Comment by GeorgeGlarakis** [comment]
Thanks a lot! That worked!
