### ISSUE TITLE
Uptrernds_monitor_web does not accept checkpoints

### ISSUE THREAD

**Issue by GeorgeGlarakis** [wasfree/terraform-provider-uptrends#16]
### Terraform Version
Terraform v1.1.0
on darwin_amd64
+ provider registry.terraform.io/wasfree/uptrends v0.1.1

### Affected Resource(s)
- uptrends_monitor_web

### Terraform Configuration Files
```hcl
resource "uptrends_monitor_web" "testing-api" {
  name                     = "api"
  check_interval           = 2
  notes                    = "Managed by Terraform"
  primary_checkpoints_only = true
  type                     = "Https"

  url                       = "https://www.google.com/"
  expected_http_status_code = 200

  selected_checkpoints {
    checkpoints       = ["Frankfurt"]
  }
}
```

### Debug Output
Plan: https://gist.github.com/GeorgeGlarakis/c3fba7f9e3cb0ff523771a7ed6d8ed50
Apply: https://gist.github.com/GeorgeGlarakis/847742d9bc7c265721fc59b450b35fbb

### Expected Behavior
What should have happened?

Accept the provided checkpoint.

### Actual Behavior
What actually happened?

Returns an error when a checkpoint is selected.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by wasfree** [comment]
HI @GeorgeGlarakis,

simular to

**Comment by wasfree** [comment]
Hi @GeorgeGlarakis,

until the error message is not directly visible use "TF_LOG=DEBUG terraform apply" > `{"Messages":[{"Message":"You must select at least 3 checkpoints."}]}`. There are at least 3 checkpoints required to provide.

```
resource "uptrends_monitor_web" "testing-api2" {
  name                     = "api2"
  check_interval           = 2
  notes                    = "Managed by Terraform"
  primary_checkpoints_only = true
  type                     = "Https"

  url                       = "https://www.google.com/"
  expected_http_status_code = 200

  selected_checkpoints {
    checkpoints       = ["Frankfurt", "Berlin", "Brussels"]
  }
}
```

**Comment by GeorgeGlarakis** [comment]
Thanks for the clarification!
